// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWeatherCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "weather",
		Short:       "Manage weather command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "mcp:open-world": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWeatherListWeatherCmd(flags))
	cmd.AddCommand(newWeatherListWeatherOutlookSelectedPhilippineCitiesCmd(flags))
	return cmd
}
