// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"context"
	"path/filepath"
	"testing"
)

func TestEscapeLike(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"plain", "plain"},
		{`a%b`, `a\%b`},
		{`a_b`, `a\_b`},
		{`a\b`, `a\\b`},
		{`%_\`, `\%\_\\`},
	}
	for _, tc := range cases {
		if got := escapeLike(tc.in); got != tc.want {
			t.Errorf("escapeLike(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestLearningsLikeFilter_Shape(t *testing.T) {
	cl, arg := learningsLikeFilter(`sci_ence`)
	if cl != `query_pattern LIKE ? ESCAPE '\'` {
		t.Fatalf("clause = %q", cl)
	}
	if arg != `%sci\_ence%` {
		t.Fatalf("arg = %q, want %%sci\\_ence%%", arg)
	}
	_, arg = learningsLikeFilter(`foo%bar`)
	if arg != `%foo\%bar%` {
		t.Fatalf("percent arg = %q", arg)
	}
}

// TestListLearnings_LikeEscapesWildcards seeds query_pattern values that still
// contain LIKE metacharacters and runs the same clause ListLearnings uses
// (learningsLikeFilter). Without ESCAPE, "sci_ence" would also match "science".
func TestListLearnings_LikeEscapesWildcards(t *testing.T) {
	dir := t.TempDir()
	s, err := Open(filepath.Join(dir, "t.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer s.Close()
	ctx := context.Background()

	seed := func(pattern, rid string) {
		t.Helper()
		_, err := s.db.ExecContext(ctx, `
INSERT INTO search_learnings (query_pattern, resource_id, action, source, confidence, last_observed_at)
VALUES (?, ?, 'boost', 'taught', 1, CURRENT_TIMESTAMP)`, pattern, rid)
		if err != nil {
			t.Fatalf("seed %s: %v", rid, err)
		}
	}
	seed("sci_ence", "A")
	seed("science", "B")
	seed("foo%bar", "C")
	seed("foobar", "D")

	listWithNeedle := func(needle string) []string {
		t.Helper()
		cl, arg := learningsLikeFilter(needle)
		q := `SELECT resource_id FROM search_learnings WHERE ` + cl + ` ORDER BY id`
		rows, err := s.db.QueryContext(ctx, q, arg)
		if err != nil {
			t.Fatalf("query %q: %v", needle, err)
		}
		defer rows.Close()
		var ids []string
		for rows.Next() {
			var id string
			if err := rows.Scan(&id); err != nil {
				t.Fatal(err)
			}
			ids = append(ids, id)
		}
		if err := rows.Err(); err != nil {
			t.Fatal(err)
		}
		return ids
	}

	if got := listWithNeedle("sci_ence"); len(got) != 1 || got[0] != "A" {
		t.Fatalf("underscore needle: want [A], got %v", got)
	}
	if got := listWithNeedle("foo%bar"); len(got) != 1 || got[0] != "C" {
		t.Fatalf("percent needle: want [C], got %v", got)
	}

	// Production ListLearnings path: NormalizeQuery + learningsLikeFilter substring.
	if _, _, err := s.UpsertLearning(ctx, UpsertLearningInput{
		Query: "portugal world cup", ResourceID: "PT", Source: LearningSourceTaught,
	}); err != nil {
		t.Fatal(err)
	}
	rows, err := s.ListLearnings(ctx, ListLearningsFilter{Query: "portugal"})
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, r := range rows {
		if r.ResourceID == "PT" {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("ListLearnings normalized substring miss: %+v", rows)
	}
}
